[Chore] Server와 SSL 인증 분리

diff --git a/.github/workflows/ssl.yml b/.github/workflows/ssl.yml
--- a/.github/workflows/ssl.yml
+++ b/.github/workflows/ssl.yml
@@ -1,9 +1,10 @@
-name: CI/CD
+name: ssl
 
 on:
-  push:
-    branches:
-      - main
+  workflow_call:
+  # schedule:
+  #   # * is a special character in YAML so you have to quote this string
+  #   - cron:  '30 5,17 * * *'
 jobs:
   frontend-deploy:
     runs-on: ubuntu-latest
@@ -56,5 +57,15 @@ jobs:
             docker rm schedulehanaro
             docker pull ${{ secrets.DOCKER_USERNAME }}/schedulehanaro
             docker run -d -p 80:80 -p 443:443 --name schedulehanaro ${{ secrets.DOCKER_USERNAME }}/schedulehanaro
-            docker cp /etc/letsencrypt/live/schedulehanaro.digital/fullchain.pem schedulehanaro:/etc/letsencrypt/live/schedulehanaro.digital/fullchain.pem
-            docker cp /etc/letsencrypt/live/schedulehanaro.digital/privkey.pem  schedulehanaro:/etc/letsencrypt/live/schedulehanaro.digital/privkey.pem
+
+            echo "Waiting for certificates to be created..."
+
+            while ! docker exec schedulehanaro [ -f /etc/letsencrypt/live/schedulehanaro.digital/fullchain.pem ]; do
+              echo "Certificate not found. Retrying in 5 seconds..."
+              sleep 5
+            done
+
+            echo "Certificates have been created! Proceeding to copy..."
+
+            docker cp schedulehanaro:/etc/letsencrypt/live/schedulehanaro.digital/fullchain.pem /etc/letsencrypt/live/schedulehanaro.digital/fullchain.pem
+            docker cp schedulehanaro:/etc/letsencrypt/live/schedulehanaro.digital/privkey.pem /etc/letsencrypt/live/schedulehanaro.digital/privkey.pem
